### PR TITLE
Don't NODE_PATH if it already defined + fix appveyor.xml for windows

### PR DESCRIPTION
**Pull request by CAMOBAP795**
- based on #35

tests crashes for base64 encoded images like this `data:image/png;base64;......`

### CODE REVIEW

**Comment by CAMOBAP795** [comment]
@ronaldtse please triage how important it is (vs. https://github.com/riboseinc/homebrew-metanorma/pull/2)

P.S. I still looking for solution for https://github.com/riboseinc/homebrew-metanorma/pull/2

**Comment by ronaldtse** [comment]
Let's fix https://github.com/riboseinc/homebrew-metanorma/pull/2 first, so that installation is possible.

**Comment by ronaldtse** [comment]
Thanks @CAMOBAP795 !

@opoudjis could you help verify the failure here? (FYI this fix is necessary for the Homebrew formula)

Here's the failure output (from https://travis-ci.org/riboseinc/metanorma/jobs/477525271):

```
Failures:
  1) Metanorma::Compile wraps HTML output
     Failure/Error: expect(File.directory?("spec/assets/test/test_images")).to be true
     
       expected true
            got false
     # ./spec/compile_spec.rb:59:in `block (2 levels) in <top (required)>'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-command-1.0.3/lib/rspec_command.rb:47:in `block (2 levels) in <module:RSpecCommand>'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-command-1.0.3/lib/rspec_command.rb:45:in `block in <module:RSpecCommand>'
Finished in 3.24 seconds (files took 0.22171 seconds to load)
17 examples, 1 failure
Failed examples:
rspec ./spec/compile_spec.rb:54 # Metanorma::Compile wraps HTML output
```

**Comment by opoudjis** [comment]
Fixed rspec for metanorma: it required metanorma-iso and its precursors to have their releases updated.

**Comment by ronaldtse** [comment]
@CAMOBAP795 the Travis tests are passing but not AppVeyor/Windows.

Error message:
```
SUCCESS: Specified value was saved.
134refreshenv
135Refreshing environment variables from registry for cmd.exe. Please wait...Finished..
136set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
137set XSLT_PROC=%ChocolateyInstall%\lib\xsltproc\dist
138bundle config build.ruby-xslt --with-xml2-include=%XSLT_PROC%\include\libxml2 --with-xslt-include=%XSLT_PROC%\include --with-xml2-lib=%XSLT_PROC%\lib --with-xslt-lib=%XSLT_PROC%\lib
139C:/Ruby25/lib/ruby/site_ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundle (Gem::GemNotFoundException)
140	from C:/Ruby25/lib/ruby/site_ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
141	from C:/Ruby25/bin/bundle:23:in `<main>'
```

Can you please help fix this?

**Comment by CAMOBAP795** [comment]
@ronaldtse sure, I will have a look in 3h

**Comment by CAMOBAP795** [comment]
@ronaldtse this issue fixed, but for now I have strange problem

```
     NoMethodError:
       undefined method `[]' for nil:NilClass
     # ./lib/metanorma/compile.rb:119:in `block in process_extensions'
     # ./lib/metanorma/compile.rb:114:in `each'
     # ./lib/metanorma/compile.rb:114:in `process_extensions'
     # ./lib/metanorma/compile.rb:18:in `compile'
     # ./spec/compile_spec.rb:18:in `block (2 levels) in <top (required)>'
  2) Metanorma::Compile processes all extensions of an asciidoc ISO document
```

It looks very strange because at this line no `[]` operator looking into this problem too

**Comment by opoudjis** [comment]
I would probably debug this easier, though I won't get to it quickly. How is this happening, so I can reproduce it?

**Comment by CAMOBAP795** [comment]
@opoudjis  The only condition is to run `bundle exec rake` on windows host (I can reproduce it on official Microsoft VM for Windows 10)

**Comment by CAMOBAP795** [comment]
@opoudjis https://developer.microsoft.com/en-us/windows/downloads/virtual-machines can help

**Comment by ronaldtse** [comment]
@CAMOBAP795 could you please help debug/fix this issue? Seems that it's related to image processing on Windows.

**Comment by CAMOBAP795** [comment]
@ronaldtse ok I will continue, and highly likely you are right. 

But still it strange that stack trace and message absolutely disappointing, is it usual in ruby world?

**Comment by CAMOBAP795** [comment]
@ronaldtse @opoudjis I have found the problem, PR will be ready in 20 min

P.S. problem was in https://github.com/riboseinc/metanorma-standoc/blob/master/lib/asciidoctor/standoc/blocks.rb#L130 it's not safe to open binary file as text file

**Comment by ronaldtse** [comment]
@CAMOBAP795 Excellent! Please help fix it if possible. Thanks!

**Comment by CAMOBAP795** [comment]
@ronaldtse sure PR on the way

**Comment by CAMOBAP795** [comment]
@ronaldtse PR is ready but I need write access to show it

**Comment by CAMOBAP795** [comment]
@ronaldtse IDK why but git command return `ERROR: Permission to riboseinc/metanorma-standoc.git denied to CAMOBAP795.` for me

**Comment by ronaldtse** [comment]
AHH -- it's the metanorma-standoc repo. It's fixed now!

**Comment by CAMOBAP795** [comment]
@ronaldtse @opoudjis done https://github.com/riboseinc/metanorma-standoc/pull/40

**Comment by ronaldtse** [comment]
OK I just trigger rebuild.

**Comment by CAMOBAP795** [comment]
> OK I just trigger rebuild.

@ronaldtse I suppose it will not work because we will need to release `metanorma-standoc` first with riboseinc/metanorma-standoc#40 merged, correct me if I'm wrong

**Comment by ronaldtse** [comment]
Let's wait for @opoudjis to confirm https://github.com/riboseinc/metanorma-standoc/pull/40 , make the release, and make it work here.

**Comment by ronaldtse** [comment]
@CAMOBAP795 can you actually use the local Gemfile to see if it works using metanorma-standoc from git? That will be much faster than waiting for @opoudjis -- and he doesn't have Windows to test.

**Comment by CAMOBAP795** [comment]
@ronaldtse good point, I will update this PR

**Comment by CAMOBAP795** [comment]
@ronaldtse according to my understanding we need to merge https://github.com/riboseinc/metanorma-standoc/pull/40 at least, because impossible to get gem from git with specific branch https://stackoverflow.com/questions/6499410/ruby-gemspec-dependency-is-possible-have-a-git-branch-dependency

In my opinion it's safe to merge https://github.com/riboseinc/metanorma-standoc/pull/40 because all tests passed there, and we already have tests which covers functionality which was changed

@ronaldtse how do you think?

**Comment by ronaldtse** [comment]
You can use a Gemfile to install the branch gem prior to gemspec if you run with bundle.

**Comment by CAMOBAP795** [comment]
@ronaldtse oh, you are right, I have looked in wrong place, PR updated now

**Comment by CAMOBAP795** [comment]
@ronaldtse Done, let me know if we should not wait for release of:
 - https://github.com/riboseinc/metanorma-standoc/pull/40
 - https://github.com/riboseinc/metanorma/pull/36

And I can return back to https://github.com/riboseinc/homebrew-metanorma/pulls ?

**Comment by ronaldtse** [comment]
Excellent! Yes let's not wait for release -- @opoudjis needs some time to do that.

**Pull request merged**
